[package]
name = "melon-net"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[package.metadata.release]
release = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
libp2p.workspace = true
minicbor.workspace = true
rand.workspace = true
serde.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

melon-bus.workspace = true
melon-core.workspace = true
melon-crypto.workspace = true
